/* Doranax Albion Holdings — single source of truth for site content.
   The build script (build/build.js) reads this file and generates every
   HTML page. Edit content here; page markup is generated, not hand-written. */

let lock = 1;
function img(keywords, w = 900, h = 650) {
  return `https://loremflickr.com/${w}/${h}/${keywords}?lock=${lock++}`;
}

const SITE = {
  name: "Doranax Albion Holdings",
  tagline: "A collective of businesses built on craft, trust, and growth.",
  email: "info@doranaxalbionholdings.com",
  heroImage: img("globe,map", 1900, 1000),
  stats: [
    { key: "sectors", value: "5", label: "sectors" },
    { key: "services", value: "25+", label: "services" },
    { key: "hq", value: "UK", label: "headquartered" },
  ],
  aboutParagraphs: [
    "Doranax Albion Holdings is a UK-based collective of businesses spanning advertising, consultancy, design and furniture, hospitality and events, and sport and wellness. Each group operates independently, with its own leadership and specialism, while drawing on the strength and resources of the wider holdings.",
    "We back businesses built on genuine craft and long-term thinking rather than short-term returns. Our approach is hands-on where it counts and hands-off where it doesn't — giving each business the room to grow on its own terms.",
  ],
  aboutImage: img("office,building", 900, 1100),
  aboutImageSecondary: img("team,meeting", 700, 900),
};

const SECTORS = [
  {
    slug: "advertising",
    name: "Doranax Advertising Group",
    tileImage: img("billboard,advertising"),
    heroImage: img("advertising,agency", 1600, 700),
    intro: "Doranax Advertising delivers integrated campaigns across print, digital, and direct channels, helping brands reach the right audience with measurable impact. From concept through execution, our teams combine creative craft with performance-driven strategy.",
    extraBlocks: [
      {
        type: "logoGrid",
        heading: "Sectors We Work With",
        items: [
          { name: "Retail", logo: img("retaillogo,brand", 300, 160) },
          { name: "Hospitality", logo: img("hospitalitylogo,brand", 300, 160) },
          { name: "Property", logo: img("propertylogo,brand", 300, 160) },
          { name: "Finance", logo: img("financelogo,brand", 300, 160) },
          { name: "Automotive", logo: img("automotivelogo,brand", 300, 160) },
          { name: "Healthcare", logo: img("healthcarelogo,brand", 300, 160) },
          { name: "Technology", logo: img("technologylogo,brand", 300, 160) },
          { name: "Manufacturing", logo: img("manufacturinglogo,brand", 300, 160) },
        ],
      },
      {
        type: "supplierGrid",
        heading: "Our Suppliers",
        items: [
          { name: "Print Partners", logo: img("printsupplier,logo", 300, 160) },
          { name: "Signage Fabricators", logo: img("signagesupplier,logo", 300, 160) },
          { name: "Media Buying", logo: img("mediasupplier,logo", 300, 160) },
          { name: "Fleet Graphics", logo: img("fleetsupplier,logo", 300, 160) },
        ],
      },
      {
        type: "jobsCta",
        heading: "Work With Doranax Advertising",
        body: "We're always looking for people who take craft and client work seriously. Get in touch to see what's currently open.",
        buttonLabel: "View Opportunities",
        buttonHref: "contact.html",
      },
    ],
    services: [
      {
        slug: "print",
        name: "Print",
        heroImage: img("printing,press", 1400, 600),
        intro: "We produce large-format, packaging, and commercial print work to exacting brand standards, from initial proofing through to final delivery. Our press partnerships mean fast turnaround without compromising on colour accuracy or finish.",
        richPage: {
          subheading: "Professional print solutions that put your brand in people's hands",
          blocks: [
            {
              type: "intro",
              paragraphs: [
                "Doranax Advertising offers full-service print production — from concept to finished product — for businesses that need physical, tangible marketing materials to back up their digital presence. Every job runs through our own design and production process, so the finish you see in the proof is the finish you get on delivery.",
                "We work with high-quality materials and press partners who turn work around fast without cutting corners on colour accuracy or finish, and our in-house design support means clients without a finished artwork file can still get a professional result. Whether it's a single business card run or a large-format storefront install, the standard doesn't change.",
                "Print still does something digital can't: it puts a brand in someone's hands, on their wall, or on their street corner, and that physical presence builds a kind of trust and recall that a banner ad doesn't. We handle everything from small business essentials to large-format signage, all under one roof.",
              ],
              images: [
                img("printingpress,factory", 900, 650),
                img("businesscards,print", 900, 650),
                img("signage,storefront", 900, 650),
              ],
            },
            {
              type: "features",
              heading: "Our Print Products",
              columns: 4,
              items: [
                {
                  name: "Business Cards",
                  subheading: "First impressions, printed properly",
                  body: "Premium stock and finishes — matte, gloss, or textured — printed to a standard that matches the rest of your brand collateral.",
                  image: img("businesscard,stack", 700, 525),
                },
                {
                  name: "Flyers",
                  subheading: "Fast, affordable, effective",
                  body: "Single and double-sided flyers for promotions, events, and campaigns, produced at volume without a drop in quality.",
                  image: img("flyer,leaflet", 700, 525),
                },
                {
                  name: "Cards",
                  subheading: "Greeting and general purpose",
                  body: "Greeting, invitation, and general-purpose cards printed on quality stock, finished to order for retail or bespoke runs.",
                  image: img("greetingcard,stationery", 700, 525),
                },
                {
                  name: "Folded Cards",
                  subheading: "More space, same finish",
                  body: "Bi-fold and tri-fold cards for menus, programmes, and invites, scored and folded to a clean, consistent edge.",
                  image: img("foldedcard,brochure", 700, 525),
                },
                {
                  name: "PVC Banners",
                  subheading: "Built for the outdoors",
                  body: "Weatherproof PVC banners for events, storefronts, and construction sites, eyeletted and finished ready to hang.",
                  image: img("pvcbanner,outdoor", 700, 525),
                },
                {
                  name: "Window Vinyl",
                  subheading: "Storefront branding that lasts",
                  body: "Cut and printed window vinyl for storefronts and vehicles, applied by our own install team for a clean, bubble-free finish.",
                  image: img("windowvinyl,storefront", 700, 525),
                },
                {
                  name: "Stretch Fabric Display Stands (Straight)",
                  subheading: "Reusable event presence",
                  body: "Portable straight-format fabric display stands for exhibitions and events, packing down small for repeat use.",
                  image: img("displaystand,exhibition", 700, 525),
                },
                {
                  name: "Water Base & A-Board Pavement Signs",
                  subheading: "Street-level visibility",
                  body: "Weighted water-base and folding A-board signs for pavement advertising, built to stand up to wind and weather.",
                  image: img("pavementsign,streetsign", 700, 525),
                },
              ],
            },
          ],
          cta: {
            heading: "Ready to Bring Your Brand to Print?",
            body: "Get in touch and our print team will help you choose the right materials and finish for your project.",
            buttonLabel: "Contact Us",
            buttonHref: "contact.html",
            form: false,
          },
        },
      },
      {
        slug: "graphic-design",
        name: "Graphic Design",
        heroImage: img("design,studio", 1400, 600),
        intro: "Our design studio builds visual identities, brand guidelines, and campaign assets that hold up across every touchpoint. We work closely with clients to ensure design decisions serve business goals, not just aesthetics.",
        gallery: [img("graphicdesign,laptop"), img("branding,design")],
      },
      {
        slug: "digital-marketing",
        name: "Digital Marketing",
        heroImage: img("digitalmarketing,laptop", 1400, 600),
        intro: "We plan and run paid, organic, and social campaigns backed by clear reporting and iterative optimisation. Our approach prioritises measurable return over vanity metrics.",
        gallery: [img("socialmedia,marketing"), img("analytics,screen")],
      },
      {
        slug: "door-to-door-marketing",
        name: "Door to Door Marketing",
        heroImage: img("doorstep,delivery", 1400, 600),
        intro: "Our field teams deliver targeted door-to-door campaigns for clients who need direct, local engagement with prospective customers. Every route is planned using demographic and geographic data to maximise conversion.",
        richPage: {
          subheading: "Direct, face-to-face marketing that gets your brand through the front door",
          blocks: [
            {
              type: "intro",
              paragraphs: [
                "Doranax Advertising runs door-to-door marketing campaigns for businesses that want direct, personal engagement with local customers — the kind of contact that cuts through digital fatigue rather than adding to it. A conversation on a doorstep still converts in a way a scrolled-past ad rarely does, and it's why door-to-door remains one of the highest-performing channels for local and regional campaigns.",
                "Every campaign is run by trained, uniformed field teams who represent your brand professionally on every visit. Territories are planned and targeted using local demographic and geographic data, so effort goes into the streets and postcodes most likely to convert rather than a blanket run across a whole area.",
                "Our reps capture data at the doorstep — interest levels, follow-up requests, and lead details — so every campaign generates a usable pipeline, not just a tally of doors knocked. All activity is run to a strict compliance and professionalism standard, with ID'd reps and clear opt-out handling on every visit.",
                "Results are tracked and reported back with real numbers: doors visited, conversations had, leads captured, and conversions closed, so you can see the return on the campaign in the same terms as any other channel.",
              ],
              images: [
                img("doortodoor,salesperson", 900, 650),
                img("fieldmarketing,uniform", 900, 650),
                img("doorstep,conversation", 900, 650),
              ],
            },
            {
              type: "process",
              heading: "How It Works",
              steps: [
                {
                  step: "1",
                  name: "Territory Mapping",
                  body: "We plan target areas using local demographic and geographic data to focus effort where it converts best.",
                },
                {
                  step: "2",
                  name: "Field Campaign",
                  body: "Trained, uniformed reps run the campaign door-to-door, representing your brand professionally on every visit.",
                },
                {
                  step: "3",
                  name: "Data Capture",
                  body: "Every conversation is logged on the doorstep — interest, follow-ups, and lead details — building a real pipeline.",
                },
                {
                  step: "4",
                  name: "Reporting",
                  body: "You receive clear reporting on doors visited, leads captured, and conversions, so the return is measurable.",
                },
              ],
            },
          ],
          cta: {
            heading: "Ready to Take Your Brand to the Doorstep?",
            body: "Get in touch and our field marketing team will help you plan a campaign for your target area.",
            buttonLabel: "Contact Us",
            buttonHref: "contact.html",
            form: false,
          },
        },
      },
      {
        slug: "content-writing",
        name: "Content Writing",
        heroImage: img("contentwriting,typing", 1400, 600),
        intro: "We produce website copy, blogs, and campaign content that reads naturally and performs — written and researched by an in-house team, not templated. Every piece is matched to brand voice before it's optimised for search or conversion.",
        richPage: {
          subheading: "Words that convert, written by people who understand your brand",
          blocks: [
            {
              type: "intro",
              paragraphs: [
                "Doranax Advertising offers professional content writing across website copy, blogs, product descriptions, ad copy, and email campaigns, built around a team of experienced copywriters rather than templated or AI-generated filler. Every brief starts with understanding the brand before a single line is written.",
                "We match tone of voice to the brand rather than the other way around — a piece written for a luxury retailer reads nothing like one written for a software startup, and that distinction is where most generic content writing falls down. Research sits behind every piece, so claims, facts, and positioning hold up under scrutiny.",
                "Content is only worth producing if it works: our writers build copy that's SEO-optimised where it needs to be and written to convert where it counts, without sacrificing readability for either. The result is content that ranks, reads well, and moves people to act.",
              ],
              images: [
                img("copywriter,laptop", 900, 650),
                img("contentteam,office", 900, 650),
                img("editing,manuscript", 900, 650),
              ],
            },
            {
              type: "features",
              heading: "What We Write",
              columns: 3,
              items: [
                {
                  name: "Website Copy",
                  body: "Homepage, landing page, and service page copy written to convert, matched to your brand voice and site structure.",
                  image: img("websitecopy,screen", 700, 525),
                },
                {
                  name: "Blog & Article Writing",
                  body: "Regular blog and article content that builds authority and keeps your site active for search and returning readers.",
                  image: img("blogwriting,notebook", 700, 525),
                },
                {
                  name: "SEO Content",
                  body: "Keyword-researched content built to rank, written to read naturally rather than stuffed for search engines.",
                  image: img("seocontent,keywords", 700, 525),
                },
                {
                  name: "Email & Newsletter Copy",
                  body: "Email sequences and newsletters written to hold attention and drive opens, clicks, and replies.",
                  image: img("emailmarketing,newsletter", 700, 525),
                },
                {
                  name: "Ad & Social Copy",
                  body: "Short-form copy for paid ads and social posts, written to stop the scroll and match platform tone.",
                  image: img("adcopy,socialpost", 700, 525),
                },
                {
                  name: "Product Descriptions",
                  body: "Product and catalogue descriptions that inform and sell, written at scale without losing consistency.",
                  image: img("productdescription,ecommerce", 700, 525),
                },
              ],
            },
          ],
          cta: {
            heading: "Ready for Content That Actually Converts?",
            body: "Get in touch and our content team will scope a package around your brand and goals.",
            buttonLabel: "Contact Us",
            buttonHref: "contact.html",
            form: false,
          },
        },
      },
      {
        slug: "social-media-marketing",
        name: "Social Media Marketing",
        heroImage: img("socialmediateam,office", 1400, 600),
        intro: "We plan, create, and manage social presence across platforms, from content production through to paid campaigns and community management. Our approach is built around measurable engagement, not vanity metrics.",
        richPage: {
          subheading: "Proactive, creative campaigns built to move the numbers that matter",
          blocks: [
            {
              type: "features",
              heading: "Our Social Media Services",
              columns: 3,
              items: [
                {
                  name: "Social Media Management",
                  body: "Day-to-day management of your channels — planning, posting, and monitoring — so your presence stays active and consistent.",
                  image: img("socialmanagement,phone", 700, 525),
                },
                {
                  name: "Social Media Advertising",
                  body: "Paid campaigns across platforms, targeted and optimised against clear performance goals rather than reach alone.",
                  image: img("socialads,targeting", 700, 525),
                },
                {
                  name: "Content Creation",
                  body: "Photography, videography, and copywriting produced specifically for social, not repurposed from other channels.",
                  image: img("contentcreation,filming", 700, 525),
                },
                {
                  name: "Community Management",
                  body: "Active moderation and response across comments and messages, keeping your brand's voice consistent in every interaction.",
                  image: img("communitymanagement,chat", 700, 525),
                },
                {
                  name: "Influencer Marketing",
                  body: "Influencer sourcing and campaign management, matched to your audience and brand rather than follower count alone.",
                  image: img("influencer,collaboration", 700, 525),
                },
                {
                  name: "Social Media Training",
                  body: "Hands-on training for in-house teams who want to build social skills and confidence internally.",
                  image: img("socialtraining,workshop", 700, 525),
                },
              ],
            },
            {
              type: "description",
              paragraphs: [
                "A strong social presence isn't optional anymore — it's often the first place a prospective customer meets your brand, and the impression it makes shapes everything that follows. We build bespoke strategies for every client rather than running the same playbook across every account, because what works for a hospitality brand doesn't work for a B2B software company.",
                "Our team works proactively across platforms, staying ahead of format and algorithm changes rather than reacting to them after performance drops. Every campaign is built around measurable engagement and business outcomes, not follower counts or vanity metrics that don't move the business forward.",
                "We work across industries — from hospitality and retail to consultancy and professional services — bringing the same level of creative and strategic rigour to every account, whatever the sector.",
              ],
            },
          ],
          cta: {
            heading: "Get In Touch",
            body: "Tell us about your brand and one of our social media strategists will be in touch to arrange a consultation.",
            buttonLabel: "Book a Consultation",
            buttonHref: "contact.html",
            form: true,
          },
        },
      },
      {
        slug: "doranax-media",
        name: "Doranax Media",
        heroImage: img("newsapp,media", 1400, 600),
        intro: "Coming Soon. Doranax Media is building an Economic News App, bringing curated business and economic news to a single, focused platform.",
        gallery: [img("newsapp,phone"), img("economicnews,chart")],
      },
      {
        slug: "doranax-booster",
        name: "Doranax Booster",
        heroImage: img("websitetraffic,growth", 1400, 600),
        intro: "Doranax Booster increases the traffic and visibility of online companies, combining paid, organic, and technical levers to grow a business's reach where it matters most.",
        gallery: [img("trafficgrowth,analytics"), img("visibility,search")],
      },
    ],
  },
  {
    slug: "consultancy",
    name: "Doranax Consultancy Group",
    tileImage: img("office,meeting"),
    heroImage: img("consulting,business", 1600, 700),
    intro: "Doranax Consultancy provides strategic and operational advisory services to businesses navigating growth, change, and international expansion. Our consultants bring hands-on sector experience rather than theoretical frameworks alone.",
    services: [
      {
        slug: "software",
        name: "Software",
        heroImage: img("coding,software", 1400, 600),
        intro: "We advise on and deliver bespoke software solutions, from systems architecture through to implementation and support. Our focus is on practical tools that solve real operational bottlenecks.",
        gallery: [img("developer,computer"), img("code,screen")],
      },
      {
        slug: "management-consultancy",
        name: "Management Consultancy",
        heroImage: img("boardroom,meeting", 1400, 600),
        intro: "We work alongside leadership teams to diagnose operational inefficiencies and implement structural change that sticks. Engagements are scoped around measurable outcomes, not lengthy reports.",
        gallery: [img("businessmeeting,office"), img("strategy,whiteboard")],
      },
      {
        slug: "recruitment",
        name: "Recruitment",
        heroImage: img("interview,office", 1400, 600),
        intro: "Our recruitment arm sources and places talent across executive, technical, and operational roles for clients in the UK and abroad. We prioritise long-term fit over speed of placement.",
        gallery: [img("handshake,business"), img("teamwork,office")],
        subServices: [
          {
            slug: "it-sector-recruitment",
            name: "IT Sector Recruitment",
            noPage: true,
            heroImage: img("techinterview,coding", 1400, 600),
            intro: "A specialist arm of our recruitment practice focused on technical hiring — developers, infrastructure, product, and IT leadership roles — where a generalist search process usually falls short.",
            panelBody: [
              "We screen for technical depth as well as fit, working with hiring managers to define the actual skill bar for a role rather than recycling a generic job spec. Candidates are assessed by people who understand the stack they'd be working in.",
              "Coverage spans permanent, contract, and interim technical hires, from individual contributor roles through to CTO and Head of Engineering searches.",
            ],
          },
        ],
      },
      {
        slug: "export-import",
        name: "Export/Import",
        heroImage: img("shippingport,cargo", 1400, 600),
        intro: "We manage the logistics, compliance, and supplier relationships required to move goods across borders efficiently. Clients rely on us to navigate customs and documentation with minimal disruption to their operations.",
        richPage: {
          subheading: "Guiding businesses through every stage of international trade",
          blocks: [
            {
              type: "intro",
              paragraphs: [
                "Doranax Consultancy's export/import desk guides businesses through each step of their international trade journey — from initial market assessment through to goods clearing customs at the other end. We handle the parts of cross-border trade that stall most businesses: regulation, documentation, and the relationships needed to keep freight moving.",
                "Our consultancy covers trade regulations, customs procedures, tariffs, and trade agreements specific to each market, alongside the global logistics needed to get goods from origin to destination reliably. We handle documentation and help plan trade finance strategies so cash flow isn't the thing that derails an otherwise sound deal.",
                "Because we work directly with in-market representatives rather than a single head-office desk, our advice reflects what's actually happening on the ground in each country, not a generic international-trade playbook.",
              ],
              images: [img("cargoship,port", 900, 650), img("customsdocuments,trade", 900, 650), img("warehouse,logistics", 900, 650)],
            },
            {
              type: "features",
              heading: "Our In-Market Representatives",
              columns: 4,
              items: [
                { name: "Poland", subheading: "Anna", body: "Our Poland-based representative for regional sourcing, compliance, and logistics coordination.", image: img("poland,warsaw", 700, 525) },
                { name: "Lithuania", subheading: "Adriana", body: "Our Lithuania-based representative supporting Baltic trade routes and customs coordination.", image: img("lithuania,vilnius", 700, 525) },
                { name: "Estonia", subheading: "Anastacia", body: "Our Estonia-based representative for Baltic and Nordic-adjacent trade support.", image: img("estonia,tallinn", 700, 525) },
                { name: "Peru", subheading: "Ariana", body: "Our Peru-based representative supporting South American sourcing and export logistics.", image: img("peru,lima", 700, 525) },
                { name: "South Korea", subheading: "Lee", body: "Our South Korea-based representative for East Asian trade relationships and manufacturing sourcing.", image: img("southkorea,seoul", 700, 525) },
                { name: "Portugal", subheading: "Sedat", body: "Our Portugal-based representative supporting Iberian and Southern European trade routes.", image: img("portugal,lisbon", 700, 525) },
                { name: "Morocco", subheading: "Becky", body: "Our Morocco-based representative for North African sourcing and cross-Mediterranean logistics.", image: img("morocco,casablanca", 700, 525) },
              ],
            },
          ],
          cta: {
            heading: "Trading Across Borders?",
            body: "Get in touch and our export/import team will scope the regulatory and logistics picture for your target market.",
            buttonLabel: "Contact Us",
            buttonHref: "contact.html",
            form: false,
          },
        },
      },
      {
        slug: "executive-coaching",
        name: "Executive Coaching",
        heroImage: img("executivecoaching,office", 1400, 600),
        intro: "We coach senior leaders and founders through the specific challenges of scaling a business — decision-making under pressure, team structure, and the personal transition that comes with growing responsibility.",
        gallery: [img("mentorship,office"), img("leadership,discussion")],
      },
      {
        slug: "concierge",
        name: "Concierge",
        heroImage: img("concierge,hotel", 1400, 600),
        intro: "A dedicated concierge service for clients requiring bespoke arrangements — travel, accommodation, and specialist procurement — handled discreetly and efficiently by a single point of contact.",
        gallery: [img("conciergedesk,luxury"), img("travelplanning,itinerary")],
      },
      {
        slug: "china",
        name: "China",
        heroImage: img("shanghai,china", 1400, 600),
        intro: "Our China desk supports clients sourcing, manufacturing, or expanding into the Chinese market, backed by on-the-ground relationships and language capability rather than a remote advisory service.",
        gallery: [img("shenzhen,factory"), img("chinabusiness,meeting")],
      },
    ],
  },
  {
    slug: "design-and-furniture",
    name: "Doranax Design and Furniture Group",
    tileImage: img("furniture,interior"),
    heroImage: img("furniture,showroom", 1600, 700),
    intro: "Doranax Design and Furniture designs, sources, and manufactures materials and pieces for residential and commercial interiors. We work with natural materials and skilled makers to deliver furnishings and finishes built to last.",
    services: [
      {
        slug: "natural-stone",
        name: "Natural Stone",
        heroImage: img("marble,stone", 1400, 600),
        intro: "We supply natural stone for flooring, worktops, and architectural features, sourced from quarries we've worked with for years. Each slab is selected for consistency of grain and finish.",
        gallery: [img("granite,quarry"), img("stonework,texture")],
      },
      {
        slug: "lighting",
        name: "Lighting",
        heroImage: img("lamp,lighting", 1400, 600),
        intro: "Our lighting range spans statement fixtures to functional task lighting, specified to suit both residential and commercial interiors. We work with clients from concept through installation.",
        gallery: [img("chandelier,interior"), img("pendant,light")],
      },
      {
        slug: "interior-design",
        name: "Interior Design",
        heroImage: img("interiordesign,livingroom", 1400, 600),
        intro: "Our interior design team delivers full-scheme design for residential and commercial spaces, from spatial planning through to final styling. We manage the process end-to-end, including trade sourcing.",
        richPage: {
          subheading: "Full-scheme interior design, managed from first sketch to final styling",
          blocks: [
            {
              type: "intro",
              paragraphs: [
                "Doranax Design and Furniture's interior design team takes on full-scheme residential and commercial projects, managing everything from spatial planning through to final styling under one point of contact. We work with the structure and light of a space first, rather than starting from a mood board, so the finished scheme actually suits how the space is used.",
                "Trade sourcing, procurement, and on-site coordination all sit within the same team that designed the scheme, which means fewer handoffs and fewer compromises between what was drawn and what gets delivered. Every project is treated as bespoke — we don't run a house style that gets applied regardless of the brief.",
              ],
              images: [img("interiordesign,sketch", 900, 650), img("furnishedliving,interior", 900, 650), img("materialsamples,swatch", 900, 650)],
            },
            {
              type: "process",
              heading: "Our Process",
              steps: [
                { step: "1", name: "Discover", body: "We spend time in the space and with the client to understand how it's actually lived in or used before any design work starts." },
                { step: "2", name: "Define", body: "We set the brief, budget, and scope in writing, so every later decision is measured against an agreed starting point." },
                { step: "3", name: "Design", body: "Spatial planning, material palette, and furnishing scheme are developed together, not as separate sign-offs." },
                { step: "4", name: "Develop", body: "Drawings are refined into a buildable specification, with trade sourcing and procurement running in parallel." },
                { step: "5", name: "Deliver", body: "We manage installation and styling on-site through to handover, so the scheme is finished to the standard it was designed to." },
              ],
            },
            {
              type: "features",
              heading: "Featured Designer",
              columns: 1,
              items: [
                {
                  name: "Christopher Hodsoll",
                  subheading: "Interior Designer",
                  body: "Christopher Hodsoll brings a distinctive, collected approach to interiors, mixing period pieces with contemporary design in schemes that feel considered rather than themed. Doranax Design and Furniture works with Christopher on select residential projects, drawing on his eye for proportion, material, and detail.",
                  image: img("interiordesigner,portrait", 700, 525),
                },
              ],
            },
          ],
          cta: {
            heading: "Planning an Interior Design Project?",
            body: "Get in touch and our team will talk through scope, timeline, and budget for your space.",
            buttonLabel: "Contact Us",
            buttonHref: "contact.html",
            form: false,
          },
        },
      },
      {
        slug: "flooring",
        name: "Flooring",
        heroImage: img("hardwoodfloor,flooring", 1400, 600),
        intro: "We supply and install flooring across timber, stone, and engineered materials, matched to the demands of each space. Our installation teams are trained to the same standard as our design specifications.",
        gallery: [img("woodfloor,interior"), img("tile,flooring")],
      },
      {
        slug: "furniture",
        name: "Furniture",
        heroImage: img("furniture,showroom", 1400, 600),
        intro: "Explore our full furniture range, crafted and curated by Doranax Furniture, on our dedicated site.",
        gallery: [img("furniture,interior"), img("furniture,design")],
        externalUrl: "https://doranaxfurniture.co.uk/",
      },
      {
        slug: "yacht-and-private-jet-interior-design",
        name: "Yacht and Private Jet Interior Design",
        heroImage: img("yachtinterior,luxury", 1400, 600),
        intro: "We design interiors for yachts and private jets, applying the same standard of material selection and spatial planning as our residential work to spaces with far tighter constraints.",
        gallery: [img("yachtcabin,interior"), img("jetcabin,luxury")],
      },
      {
        slug: "drinks-cabinet",
        name: "Drinks Cabinet",
        heroImage: img("drinkscabinet,furniture", 1400, 600),
        intro: "Our bespoke drinks cabinets are designed and built to order, from compact home-bar pieces to full entertaining units finished in a choice of woods and metals.",
        gallery: [img("barcabinet,wood"), img("homedrinksbar,furniture")],
      },
      {
        slug: "bronze-coffee-tables-wooden-boxes",
        name: "Bronze, Coffee Tables & Wooden Boxes",
        heroImage: img("bronzesculpture,coffeetable", 1400, 600),
        intro: "A collection of three of our smaller furniture and object lines, each made to order — bronze sculpture pieces, coffee tables, and custom wooden boxes.",
        gallery: [img("bronzefigure,sculpture"), img("coffeetable,livingroom")],
        subServices: [
          {
            slug: "bronze",
            name: "Bronze Sculptures",
            noPage: true,
            heroImage: img("bronzesculpture,art", 1400, 600),
            intro: "Cast bronze sculpture pieces for residential and commercial interiors, made to order in a range of scales and finishes.",
            panelBody: [
              "Each piece is cast and finished by hand, so texture and patina vary slightly by piece — the kind of variation that reads as craft rather than inconsistency.",
            ],
          },
          {
            slug: "coffee-tables",
            name: "Coffee Tables",
            noPage: true,
            heroImage: img("coffeetable,design", 1400, 600),
            intro: "Coffee tables built to order in solid wood, stone, and mixed-material designs, sized and finished to fit the room they're going into.",
            panelBody: [
              "We work from a set of house designs or a client's own reference, adjusting proportions, material, and finish for the specific space.",
            ],
          },
          {
            slug: "custom-wooden-boxes",
            name: "Custom Wooden Boxes",
            noPage: true,
            heroImage: img("woodenbox,craftsmanship", 1400, 600),
            intro: "Custom wooden boxes for storage, presentation, and gifting, built in a choice of timbers with optional lining, engraving, and hardware.",
            panelBody: [
              "Sizes and finishes are made to order, from small keepsake boxes through to larger storage and display pieces.",
            ],
          },
        ],
      },
    ],
  },
  {
    slug: "hospitality-events",
    name: "Doranax Hospitality & Events Group",
    tileImage: img("event,hospitality"),
    heroImage: img("hotel,event", 1600, 700),
    intro: "Doranax Hospitality & Events operates across property, food & beverage, and live event production, delivering experiences that meet a consistently high standard. We manage every layer of an event or venue, from planning through to delivery.",
    services: [
      {
        slug: "property",
        name: "Property",
        heroImage: img("realestate,building", 1400, 600),
        intro: "We manage and develop hospitality properties, from acquisition through to day-to-day operation, with a focus on guest experience and long-term asset value.",
        gallery: [img("hotel,lobby"), img("architecture,building")],
        subServices: [
          {
            slug: "venue-hire",
            name: "Venue Hire",
            noPage: true,
            heroImage: img("eventvenue,hire", 1400, 600),
            intro: "We source and manage venue hire for events of every scale, from intimate private dinners to large-scale corporate functions.",
            panelBody: ["Our venue network spans hotels, private estates, and dedicated event spaces, matched to the brief and guest count."],
          },
          {
            slug: "office-sharing",
            name: "Office Sharing",
            noPage: true,
            heroImage: img("coworking,office", 1400, 600),
            intro: "Flexible shared office space for businesses that want a professional base without committing to a full lease.",
            panelBody: ["Desks, private offices, and meeting rooms are available on flexible terms, with reception and facilities managed for you."],
          },
          {
            slug: "dark-kitchen-hire",
            name: "Dark Kitchen Hire",
            noPage: true,
            heroImage: img("commercialkitchen,delivery", 1400, 600),
            intro: "Commercial kitchen space for delivery-only food brands, fitted and ready to operate without the overhead of a full restaurant site.",
            panelBody: ["Space is available on flexible terms, sized for single operators through to multi-brand kitchens."],
          },
          {
            slug: "bnb-management",
            name: "BnB Management",
            noPage: true,
            heroImage: img("bnbinterior,hospitality", 1400, 600),
            intro: "End-to-end management for short-let and BnB properties — pricing, listing, guest vetting, messaging, cleaning coordination, and maintenance — so owners get the return without doing the work themselves.",
            panelBody: [
              "We handle dynamic pricing and listing creation across major platforms, guest vetting and communication around the clock, and coordinate cleaning and maintenance between stays.",
            ],
          },
          {
            slug: "property-service",
            name: "Property Service",
            noPage: true,
            heroImage: img("propertymaintenance,service", 1400, 600),
            intro: "General property services for owners and managers — maintenance, inspections, and day-to-day upkeep — coordinated through a single point of contact.",
            panelBody: ["Scheduled and on-demand visits are arranged directly with our property team, with reporting back to the owner after every visit."],
          },
          {
            slug: "brum-real-estate",
            name: "Brum Real Estate",
            noPage: true,
            heroImage: img("birminghamproperty,realestate", 1400, 600),
            intro: "Our Birmingham-focused real estate arm handles acquisition, letting, and management for residential and commercial property across the city.",
            panelBody: ["Local market knowledge sits at the centre of every instruction, from sourcing through to ongoing management."],
          },
          {
            slug: "cleaning",
            name: "Cleaning",
            noPage: true,
            heroImage: img("professionalcleaning,hospitality", 1400, 600),
            intro: "Professional cleaning services for hospitality and residential properties, scheduled around occupancy and turnaround times.",
            panelBody: ["Teams are trained to hospitality-grade standards, with turnaround cleans built around check-in/check-out schedules where needed."],
          },
        ],
      },
      {
        slug: "vehicle-hire",
        name: "Vehicle Hire",
        heroImage: img("luxurycar,yacht", 1400, 600),
        intro: "We arrange vehicle hire for events and private clients — cars, yachts, helicopters, and private jets — matched to the occasion and handled door to door.",
        gallery: [img("luxurycar,rental"), img("yacht,marina")],
        subServices: [
          {
            slug: "yacht-hire",
            name: "Yacht Hire",
            noPage: true,
            heroImage: img("yachtcharter,sailing", 1400, 600),
            intro: "Charter a yacht for a day, a weekend, or a full itinerary, crewed and provisioned to the standard of the occasion.",
            panelBody: ["Available across our partner fleet, matched to guest numbers and route."],
          },
          {
            slug: "yacht-share",
            name: "Yacht Share",
            noPage: true,
            heroImage: img("yachtshare,sailing", 1400, 600),
            intro: "Our yacht share programme gives members access to a managed fleet without the cost or hassle of sole ownership.",
            panelBody: ["Membership covers scheduled access, crew, and maintenance, so owners get the yacht without carrying it as a full-time asset."],
          },
          {
            slug: "car-hire",
            name: "Car Hire",
            noPage: true,
            heroImage: img("luxurycar,rental", 1400, 600),
            intro: "Luxury and executive car hire for events and private clients, delivered and collected wherever the occasion requires.",
            panelBody: ["Chauffeur-driven or self-drive options are available, with a fleet ranging from executive saloons to occasion vehicles."],
          },
          {
            slug: "helicopter",
            name: "Helicopter",
            noPage: true,
            heroImage: img("helicopter,flight", 1400, 600),
            intro: "Helicopter charter for clients who need fast, flexible travel between locations on their own schedule.",
            panelBody: ["Booked point-to-point or as part of a wider travel itinerary, subject to routing and availability."],
          },
          {
            slug: "private-jets",
            name: "Private Jets",
            noPage: true,
            heroImage: img("privatejet,airport", 1400, 600),
            intro: "Private jet charter arranged for discreet, flexible travel, from single-leg bookings to full multi-stop itineraries.",
            panelBody: ["Aircraft are matched to party size and route, with full itinerary planning handled on your behalf."],
          },
        ],
      },
      {
        slug: "yacht-sale",
        featured: true,
        name: "Yacht Sale",
        heroImage: img("yachtforsale,marina", 1400, 600),
        intro: "Browse a selection of yachts currently available through our network, and get in touch with our brokerage to discuss options.",
        richPage: {
              subheading: "Browse our broker's current yacht listings across the Turkish Riviera",
              blocks: [
                {
                  type: "yachtGrid",
                  heading: "Broker's Yachts for Sale",
                  intro: "A selection of motor yachts currently available through our brokerage, from recent-build models ready for immediate handover to long-standing favourites. Get in touch with the broker below to discuss any listing.",
                  items: [
                    {
                      name: "Inspiration",
                      priceDisplay: "€4,900,000",
                      location: "Marmaris, Mugla, Turkey",
                      cabins: 4,
                      year: 2024,
                      length: `85' 4" ft`,
                      builder: "Numarine",
                      badge: `2024 NUMARINE 85' 4"`,
                      image: img("motoryacht,numarine", 1000, 650),
                    },
                    {
                      name: "Honey Badger",
                      priceDisplay: "€3,150,000",
                      location: "Bodrum, Mugla, Turkey",
                      cabins: 4,
                      year: 2012,
                      length: `91' 9" ft`,
                      builder: "Pershing",
                      badge: `2012 PERSHING 91' 9"`,
                      image: img("motoryacht,pershing", 1000, 650),
                    },
                    {
                      name: "Virtus",
                      priceDisplay: "€2,000,000",
                      location: "Marmaris, Mugla, Turkey",
                      cabins: 4,
                      year: 2021,
                      length: `72' 11" ft`,
                      builder: "Galeon Yachts",
                      badge: `2021 GALEON YACHTS 72' 11"`,
                      image: img("motoryacht,galeon", 1000, 650),
                    },
                    {
                      name: "Nine Nine Wine",
                      priceDisplay: "€1,750,000",
                      location: "Gocek, Mugla, Turkey",
                      cabins: 4,
                      year: 2016,
                      length: `66' 2" ft`,
                      builder: "Azimut Yachts",
                      badge: `2016 AZIMUT YACHTS 66' 2"`,
                      image: img("motoryacht,azimut", 1000, 650),
                    },
                    {
                      name: "Twins PC",
                      priceDisplay: "€700,000",
                      location: "Marmaris, Mugla, Turkey",
                      cabins: 4,
                      year: 1996,
                      length: `81' 11" ft`,
                      builder: "Sanlorenzo Yachts",
                      badge: `1996 SANLORENZO YACHTS 81' 11"`,
                      image: img("motoryacht,sanlorenzo", 1000, 650),
                    },
                    {
                      name: "Hakuna Matata",
                      priceDisplay: "€275,000",
                      location: "Gocek, Mugla, Turkey",
                      cabins: 3,
                      year: 2004,
                      length: `58' 10" ft`,
                      builder: "Fairline",
                      badge: `2004 FAIRLINE 58' 10"`,
                      image: img("motoryacht,fairline", 1000, 650),
                    },
                  ],
                },
                {
                  type: "brokerContact",
                  name: "Haluk Gundogdu",
                  title: "Naval Architect / Yacht Broker",
                  company: "Yacht Sales Center AS",
                  location: "Kadikoy, Istanbul, Turkey",
                  officePhone: "+90 216 755 8080",
                  mobilePhone: "+90 542 643 3873",
                  email: null,
                },
              ],
            },
          },
      {
        slug: "talent-management",
        name: "Talent Management",
        heroImage: img("talentagency,management", 1400, 600),
        intro: "We manage talent bookings for events and campaigns, handling contracts, logistics, and on-the-day coordination — including DJs, speakers, and models under one roster.",
        gallery: [img("talent,agency"), img("performer,management")],
        subServices: [
          {
            slug: "bruce-daisley",
            name: "Bruce Daisley",
            noPage: true,
            heroImage: img("keynotespeaker,conference", 1400, 600),
            intro: "Bruce Daisley — former Twitter EMEA VP, author, and speaker on workplace culture — is represented for speaking engagements through Doranax Talent Management.",
            panelBody: [
              "Bruce speaks on culture, leadership, and the future of work, drawing on his time leading Twitter's European business and his ongoing research and writing on workplace culture. Doranax Talent Management handles booking, logistics, and coordination for his speaking engagements.",
            ],
          },
          {
            slug: "dj-hire",
            name: "DJ Hire",
            noPage: true,
            heroImage: img("dj,nightclub", 1400, 600),
            intro: "We book DJs for private and corporate events, matching style and experience to the brief, with full sound production available.",
            panelBody: ["From intimate private parties to full corporate productions, sets and sound are scoped to the venue and guest list."],
          },
          {
            slug: "speakers",
            name: "Speakers",
            noPage: true,
            heroImage: img("conferencespeaker,stage", 1400, 600),
            intro: "We source and book keynote and panel speakers for corporate events and conferences, matched to audience and subject matter.",
            panelBody: ["Coverage spans business, culture, and industry-specific expertise — tell us the audience and topic and we'll shortlist speakers to fit."],
          },
          {
            slug: "model-management",
            name: "Model Management",
            noPage: true,
            heroImage: img("fashionmodel,agency", 1400, 600),
            intro: "Our model management arm represents and books models for campaigns, shows, and events, with casting handled in-house.",
            panelBody: ["Casting is run directly by our team, matched to brief, market, and shoot or show requirements."],
          },
        ],
      },
      {
        slug: "events-production",
        name: "Event Production",
        heroImage: img("eventplanning,organisation", 1400, 600),
        intro: "We plan and produce corporate and private events end-to-end — organisation, hostessing, and photography — for clients who need it done right the first time.",
        gallery: [img("eventplanner,clipboard"), img("eventsetup,organisation")],
        subServices: [
          {
            slug: "event-organisation",
            name: "Event Organisation",
            noPage: true,
            heroImage: img("eventplanning,organisation", 1400, 600),
            intro: "Dreaming up an incredible celebration? We're masters at designing and executing unforgettable social and corporate event experiences.",
            panelBody: [
              "We transform spaces, curate exciting entertainment, and manage logistics — no crowd is too large and no idea is too wild. From concept to cueing the music to end-of-the-night concessions, we leave your guests wowed and watching their mailboxes for next year's invitation.",
            ],
          },
          {
            slug: "event-hostess",
            name: "Event Hostess",
            noPage: true,
            heroImage: img("eventhostess,greeting", 1400, 600),
            intro: "We provide trained hostesses for events, covering guest reception, registration, and on-floor support.",
            panelBody: ["Staff are briefed on the event and brand ahead of time, so guest-facing standards stay consistent from arrival to close."],
          },
          {
            slug: "event-photography",
            name: "Event Photography",
            noPage: true,
            heroImage: img("eventphotographer,camera", 1400, 600),
            intro: "Our event photography team covers corporate and private events, delivering a fast turnaround without compromising on quality.",
            panelBody: ["Coverage is scoped to the event — full-day production or a focused set of key moments — with edited galleries delivered fast."],
          },
        ],
      },
      {
        slug: "events-lifestyle",
        name: "Lifestyle & Leisure",
        heroImage: img("luxurytravel,resort", 1400, 600),
        intro: "A collection of our lifestyle and leisure offerings for private clients — travel, dance, photography and coffee courses, and members' access.",
        gallery: [img("privatevilla,travel"), img("privateclub,lounge")],
        subServices: [
          {
            slug: "luxury-travel",
            name: "Luxury Travel",
            noPage: true,
            heroImage: img("luxurytravel,resort", 1400, 600),
            intro: "We plan luxury travel itineraries for private clients, from villa stays to bespoke tours, handled end-to-end by a dedicated travel desk.",
            panelBody: ["Every itinerary is built around the client, not a fixed package — get in touch with dates and a rough brief to start planning."],
          },
          {
            slug: "gourmet-travels",
            name: "Gourmet Travels",
            noPage: true,
            heroImage: img("gourmettravel,foodie", 1400, 600),
            intro: "Our gourmet travel packages combine destination dining with curated itineraries, built for clients who travel for the food.",
            panelBody: ["Itineraries are built around chef's-table bookings, food markets, and regional specialities rather than a generic sightseeing route."],
          },
          {
            slug: "dance",
            name: "Dance",
            noPage: true,
            heroImage: img("danceclass,studio", 1400, 600),
            intro: "We run dance classes for private and corporate groups, from beginner sessions to choreographed routines for events. Contact Anna to arrange classes.",
            panelBody: ["Sessions run for individuals, private groups, or as part of a wider event booking."],
          },
          {
            slug: "photography-courses",
            name: "Photography Courses",
            noPage: true,
            heroImage: img("photographyclass,camera", 1400, 600),
            intro: "We run photography courses for all levels, covering technique, composition, and editing, taught by working photographers.",
            panelBody: ["Small-group sessions cover camera fundamentals through to editing, taught hands-on rather than lecture-style."],
          },
          {
            slug: "coffee-courses",
            name: "Coffee Courses",
            noPage: true,
            heroImage: img("coffeeclass,beginner", 1400, 600),
            intro: "Our beginner coffee courses introduce guests to brewing fundamentals, tasting, and basic latte art in a relaxed setting.",
            panelBody: ["A relaxed introduction to brewing and tasting, aimed at enthusiasts rather than trade professionals."],
          },
          {
            slug: "private-members-club",
            name: "Private Members Club",
            noPage: true,
            heroImage: img("membersclub,lounge", 1400, 600),
            intro: "Our private members club offers a discreet space and calendar of events for members, with reciprocal access across partner venues.",
            panelBody: ["Membership includes reciprocal access across partner venues and a regular calendar of members' events."],
          },
        ],
      },
      {
        slug: "food-beverage",
        name: "Food & Beverage",
        heroImage: img("restaurant,dining", 1400, 600),
        intro: "We've curated a dynamic food and beverage portfolio, ranging from restaurants, bars, cafes, beach clubs, lounges, and in-room dining. Our F&B division designs and operates dining concepts, from menu development through to service standards, for venues and events alike.",
        gallery: [img("chef,kitchen"), img("cocktail,bar")],
        subServices: [
          {
            slug: "spirits",
            name: "Spirits (Gin, Rum and Vodka)",
            noPage: true,
            heroImage: img("gin,distillery", 1400, 600),
            intro: "Coming Soon. A small-batch spirits line covering gin, rum, and vodka, currently in development with a distillery partner.",
            panelBody: ["Product details and launch timing will follow once the partnership and recipes are confirmed."],
          },
          {
            slug: "food-advisor",
            name: "Food Advisor",
            noPage: true,
            heroImage: img("restaurantconsulting,advisor", 1400, 600),
            intro: "Our food advisory service helps venues and operators refine menus, sourcing, and kitchen operations, drawing on hands-on F&B experience across the group.",
            panelBody: ["Engagements range from a single menu review through to a full operational audit of a kitchen or venue."],
          },
          {
            slug: "recruitment",
            name: "Recruitment for Food & Beverage",
            noPage: true,
            heroImage: img("hospitalityinterview,recruitment", 1400, 600),
            intro: "We source and place chefs, front-of-house staff, and management for restaurants, bars, and hotels, matching candidates to the standard each venue demands.",
            panelBody: ["Coverage spans permanent and temporary hires, from kitchen porters through to head chef and general manager roles."],
          },
          {
            slug: "hamburger-pizza-app",
            name: "Hamburger and Pizza App",
            noPage: true,
            heroImage: img("foodapp,delivery", 1400, 600),
            intro: "Coming Soon. An ordering app concept for our burger and pizza concepts, currently in early development.",
            panelBody: ["More detail will follow as the concept is scoped and confirmed."],
          },
          {
            slug: "coffee-and-barista-courses",
            name: "Coffee and Barista Courses",
            noPage: true,
            heroImage: img("baristatraining,coffee", 1400, 600),
            intro: "Our barista training programme covers espresso extraction, milk texturing, and bar service standards, run by working baristas for staff who need to hit a professional standard fast.",
            panelBody: ["Courses are run for individual trainees or as a full staff onboarding programme for a new venue."],
          },
          {
            slug: "coffee-beans",
            name: "Coffee Beans",
            noPage: true,
            heroImage: img("coffeebeans,roastery", 1400, 600),
            intro: "We source and roast coffee beans for venues and retail, offering a range of blends and single origins with consistent supply for busy service.",
            panelBody: ["Wholesale and retail-bagged supply are both available, with consistent roast profiles maintained batch to batch."],
          },
          {
            slug: "cake",
            name: "Cake",
            noPage: true,
            heroImage: img("cake,bakery", 1400, 600),
            intro: "Our bakery produces cakes for venues, events, and retail, from everyday counter stock to bespoke celebration pieces made to order.",
            panelBody: [
              "Every cake is baked from scratch to order, with a consultation up front to lock in flavour, size, and design before anything goes in the oven. We cover birthday and celebration designs alongside occasion-specific work for weddings, corporate events, and baby showers.",
              "Delivery and collection are both available, timed around your event so the cake arrives in the condition it left the kitchen in.",
            ],
          },
          {
            slug: "burger",
            name: "Burger",
            noPage: true,
            heroImage: img("smashburger,restaurant", 1400, 600),
            intro: "Our burger concept keeps things simple — a small, tightly run menu built around a smash-style patty, quality ingredients, and fast, precise cooking.",
            panelBody: [
              "No sprawling menu, no gimmicks — just a format we've deliberately kept simple so it can be executed consistently, service after service, for customers who want something good and quick rather than a long wait for a novelty burger.",
            ],
          },
          {
            slug: "breakfast-club",
            name: "Breakfast Club",
            noPage: true,
            heroImage: img("breakfast,cafe", 1400, 600),
            intro: "Coming Soon. A breakfast and brunch concept currently in development for our F&B portfolio.",
            panelBody: ["Menu and venue details will be confirmed closer to launch."],
          },
          {
            slug: "protein-powder",
            name: "Protein Powder",
            noPage: true,
            heroImage: img("proteinshake,cafe", 1400, 600),
            intro: "A protein powder line for our cafes and venues, designed to go straight into shakes and smoothies at the counter rather than as a take-home retail product.",
            panelBody: [
              "This sits alongside, and is distinct from, the performance nutrition range under Doranax Sports & Wellness — this line is built for in-venue use, not home training.",
            ],
          },
        ],
      },
      {
        slug: "workwear",
        name: "Workwear",
        heroImage: img("uniform,staff", 1400, 600),
        intro: "We supply branded and functional workwear for hospitality teams, balancing durability with a presentation standard that reflects the venues we serve.",
        gallery: [img("chef,uniform"), img("hotelstaff,waiter")],
      },
    ],
  },
  {
    slug: "sports-wellness",
    name: "Doranax Sports & Wellness Group",
    tileImage: img("yoga,wellness"),
    heroImage: img("yoga,fitness", 1600, 700),
    intro: "Doranax Sports & Wellness brings together movement, nutrition, and self-care under one roof, built around a genuine wellbeing philosophy rather than a fitness trend. Our offering spans practice, product, and retreat experiences.",
    services: [
      {
        slug: "yoga",
        name: "Yoga",
        heroImage: img("yoga,studio", 1400, 600),
        intro: "We give Yoga Lessons. Our classes and teacher training run across a range of styles and levels, led by instructors with years of teaching experience, designed to be accessible without diluting the practice.",
        gallery: [img("yogamat,meditation"), img("stretching,fitness")],
        subServices: [
          {
            slug: "yoga-mats",
            name: "Yoga Mats",
            noPage: true,
            heroImage: img("yogamat,product", 1400, 600),
            intro: "Our yoga mats are designed for grip and durability across styles, from restorative to hot yoga, sold through studios and online.",
            panelBody: [
              "The range spans travel-weight mats through to thick cushioned studio mats in cork, natural rubber, and recycled foam — get in touch for current stock and studio bulk-order pricing.",
            ],
          },
          {
            slug: "yoga-blocks",
            name: "Yoga Blocks",
            noPage: true,
            heroImage: img("yogablock,product", 1400, 600),
            intro: "Our yoga blocks support alignment and accessibility in practice, made from durable, lightweight foam and cork.",
            panelBody: [
              "Sold individually or in studio sets, sized to suit both restorative practice and more demanding alignment work.",
            ],
          },
          {
            slug: "tote-bags",
            name: "Tote Bags",
            noPage: true,
            heroImage: img("totebag,yoga", 1400, 600),
            intro: "Our yoga tote bags are built to carry a mat and kit comfortably, finished with studio branding for retail and giveaways.",
            panelBody: [
              "Available as a retail line or branded for studios running their own giveaways and member gifting.",
            ],
          },
        ],
      },
      {
        slug: "doranax-athletics",
        name: "Doranax Athletics",
        heroImage: img("activewear,fashion", 1400, 600),
        intro: "Doranax Athletics produces performance and lifestyle apparel and merchandise designed for movement, made from sustainably sourced materials wherever possible.",
        richPage: {
          subheading: "Performance and lifestyle apparel, made from sustainably sourced materials",
          blocks: [
            {
              type: "intro",
              paragraphs: [
                "The Doranax Athletics range covers everyday performance and lifestyle apparel alongside a branded merchandise line, built for training, travel, and everyday wear. Every piece is produced with sustainably sourced materials wherever the category allows.",
                "Retail and team/bulk orders are both available across the full range below — get in touch for custom branding or a studio order.",
              ],
              images: [img("activewearflatlay,apparel", 900, 650), img("sportswearrack,retail", 900, 650), img("fabrictexture,textile", 900, 650)],
            },
            {
              type: "productGrid",
              heading: "Shop Doranax Athletics",
              items: [
                { name: "Performance T-Shirt", price: 28.0, image: img("tshirt,apparel", 700, 700) },
                { name: "Lifestyle T-Shirt", price: 24.0, image: img("tshirtprint,apparel", 700, 700) },
                { name: "Training Hoodie", price: 58.0, image: img("hoodie,apparel", 700, 700) },
                { name: "Lightweight Zip Hoodie", price: 62.0, image: img("hoodierack,clothing", 700, 700) },
                { name: "Branded Canvas Tote", price: 18.0, image: img("totebag,merch", 700, 700) },
                { name: "Everyday Tote", price: 16.0, image: img("totebagmerch,product", 700, 700) },
                { name: "Stainless Travel Mug", price: 22.0, image: img("travelmug,product", 700, 700) },
                { name: "Insulated Travel Mug", price: 26.0, image: img("thermosmug,travel", 700, 700) },
                { name: "Reusable Drink Bottle", price: 20.0, image: img("waterbottle,product", 700, 700) },
                { name: "Insulated Sports Bottle", price: 24.0, image: img("sportsbottle,hydration", 700, 700) },
                { name: "Performance Cap", price: 19.0, image: img("baseballcap,apparel", 700, 700) },
                { name: "Classic Fit Cap", price: 17.0, image: img("capmerch,apparel", 700, 700), soldOut: true },
              ],
            },
          ],
          cta: {
            heading: "Looking for a Team or Bulk Order?",
            body: "Get in touch and our team will help you put together a custom-branded order.",
            buttonLabel: "Contact Us",
            buttonHref: "contact.html",
            form: false,
          },
        },
      },
      {
        slug: "skincare",
        name: "Skincare",
        heroImage: img("skincare,cosmetics", 1400, 600),
        intro: "We work with international skincare brands to bring a formulated, effective range to our clients, suited to daily use and developed in partnership with formulation specialists.",
        gallery: [img("spa,beauty"), img("serum,skincare")],
      },
      {
        slug: "protein",
        name: "Protein",
        heroImage: img("proteinpowder,nutrition", 1400, 600),
        intro: "Our performance nutrition line is formulated to support training and recovery, with a focus on ingredient transparency and taste rather than filler and marketing claims.",
        gallery: [img("smoothie,health"), img("gym,fitness")],
      },
      {
        slug: "retreat",
        name: "Retreat",
        heroImage: img("retreat,nature", 1400, 600),
        intro: "We host wellness retreats that combine movement, rest, and nutrition in a small-group setting, designed for genuine recovery rather than a packed itinerary.",
        gallery: [img("mountains,retreat"), img("meditation,nature")],
        subServices: [
          {
            slug: "morocco",
            name: "Morocco",
            noPage: true,
            heroImage: img("morocco,retreat", 1400, 600),
            intro: "Our Morocco retreat combines desert and riad settings with daily movement and rest, run in small groups for a genuinely restorative pace.",
            panelBody: [
              "Days are built around morning practice, guided rest, and communal meals, with the desert and riad settings doing the rest of the work.",
            ],
          },
          {
            slug: "turkiye",
            name: "Turkiye",
            noPage: true,
            heroImage: img("turkey,retreat", 1400, 600),
            intro: "Our Turkiye retreat pairs coastal and Cappadocia settings with a programme of movement, rest, and nutrition in a small-group format.",
            panelBody: [
              "The itinerary moves between coast and Cappadocia across the retreat, balancing structured sessions with genuine unstructured downtime.",
            ],
          },
        ],
      },
    ],
  },
];

const CONTACT = {
  heroImage: img("office,uk", 1600, 500),
  intro: "For enquiries across any of our sectors, get in touch and a member of the relevant team will respond directly.",
};

module.exports = { SITE, SECTORS, CONTACT };
